language: objective-c
osx_image: xcode8.1
rvm:
    2.2.5

before_install:
    - gem install xcpretty
script:
    - xcodebuild test -project ImageViewModel.xcodeproj -scheme ImageViewModel -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0'
