language: objective-c
osx_image: xcode7.2
xcode_project: ImageViewModel/ImageViewModel.xcodeproj 
xcode_scheme: ImageViewModel 
xcode_sdk: iphonesimulator9.2
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform ios

