language: objective-c
osx_image: xcode7.3
xcode_project: ImageViewModel.xcodeproj 
xcode_scheme: ImageViewModel 
xcode_sdk: iphonesimulator9.3
before_script:
  - carthage bootstrap --platform ios --no-use-binaries

