language: objective-c
osx_image: xcode7.2
xcode_project: ImageViewModel/ImageViewModel.xcodeproj 
xcode_scheme: ImageViewModel 
xcode_sdk: iphonesimulator9.2
before_install:
	- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11.0/Carthage.pkg"
	- sudo installer -pkg "Carthage.pkg" -target /
	- rm "Carthage.pkg"